import type { Metadata } from 'next'
import './globals.css'

import {SiteHeader} from '@/components/site-header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-'>
      <body className = 'bg-background text-black selection:bg-teal-300 dark:bg-neutral-900 \
      dark:text-white dark:selection:bg-pink-500 dark:selection:text-white'>
        <div className=''>
          <SiteHeader/>
          {children}
        </div>
        
        </body>
    </html>
  )
}
